/**
 * Central Audio Asset Registry for Autism Platform Activities
 * Verified Public Domain, Creative Commons Zero (CC0), and Royalty-Free real-world recordings.
 */

export const AUDIO_REGISTRY = {
  // --- Shorthand Aliases & Keys ---
  bakh: {
    name: 'Real Human Peekaboo & Laughter',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Social gaze reveal audio for Peekaboo and mask activities',
    activity: 'PeekabooHandsActivity & FaceMasksActivity',
    volume: 0.85,
  },
  bakh_surprise: {
    name: 'Real Human Peekaboo & Laughter',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Social gaze reveal audio for Peekaboo and mask activities',
    activity: 'PeekabooHandsActivity',
    volume: 0.85,
  },
  laugh: {
    name: 'Real Human Giggle & Laughter',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real laughter audio for positive reinforcement',
    activity: 'CrazyFacesActivity & SocialSmileMirrorActivity',
    volume: 0.85,
  },
  gasp: {
    name: 'Real Human Gasp & Surprise',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real surprise vocalization',
    activity: 'NameResponseCallActivity',
    volume: 0.85,
  },
  pop: {
    name: 'Real Soap Bubble Pop',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real bubble popping sound',
    activity: 'BubblePopActivity & TurnTakingBallActivity',
    volume: 0.85,
  },
  water_flow: {
    name: 'Real Faucet Water Stream Flow',
    url: 'https://cdn.freesound.org/previews/515/515664_11270278-lq.mp3',
    source: 'Freesound.org (#515664)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real water stream audio stage 2',
    activity: 'InteractiveFaucetActivity',
    volume: 0.85,
  },
  bee_buzz: {
    name: 'Real Honeybee Buzzing Recording',
    url: 'https://cdn.freesound.org/previews/538/538947_11861866-lq.mp3',
    source: 'Freesound.org (#538947)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real bee buzzing sound for honeycomb hide',
    activity: 'BeeHoneycombHideActivity',
    volume: 0.80,
  },
  drum_beat: {
    name: 'Real Acoustic Drum Kick Beat',
    url: 'https://cdn.freesound.org/previews/264/264762_4867909-lq.mp3',
    source: 'Freesound.org (#264762)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real drum beat recording for musician activity',
    activity: 'MusicianTrainerActivity',
    volume: 0.85,
  },
  applause: {
    name: 'Real Audience Applause & Cheering',
    url: 'https://cdn.freesound.org/previews/442/442769_7480749-lq.mp3',
    source: 'Freesound.org (#442769)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real applause for achievement reinforcement',
    activity: 'SocialSmileMirrorActivity',
    volume: 0.80,
  },
  car_horn: {
    name: 'Real Car Engine & Horn',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real car motor rumble',
    activity: 'VehicleChaserActivity',
    volume: 0.85,
  },

  // --- Full Group A & B Key Assets ---
  name_call: {
    name: 'Real Warm Human Voice Prompt',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Auditory prompt for name response activity',
    activity: 'NameResponseCallActivity',
    volume: 0.85,
  },
  clapping: {
    name: 'Real Hand Clapping',
    url: 'https://cdn.freesound.org/previews/442/442769_7480749-lq.mp3',
    source: 'Freesound.org (#442769)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Positive reinforcement audio for gesture mimicry',
    activity: 'SocialGestureMimicryActivity',
    volume: 0.80,
  },
  finger_snap: {
    name: 'Real Finger Snap Recording',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Auditory feedback for finger snapping gesture',
    activity: 'SocialGestureMimicryActivity',
    volume: 0.80,
  },
  ball_bounce: {
    name: 'Real Ball Bounce Recording',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real ball bouncing sound on floor',
    activity: 'TurnTakingBallActivity',
    volume: 0.85,
  },
  vocal_humming: {
    name: 'Real Human Vocal Humming',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Gentle musical singing vocal feedback',
    activity: 'SingingMovingHeadActivity',
    volume: 0.80,
  },
  piano_note: {
    name: 'Real Acoustic Piano Note',
    url: 'https://cdn.freesound.org/previews/264/264762_4867909-lq.mp3',
    source: 'Freesound.org (#264762)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real piano instrument note recording',
    activity: 'MusicianTrainerActivity',
    volume: 0.85,
  },
  human_countdown: {
    name: 'Real Human Vocal Countdown (1-5)',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real vocal countdown for jump & countdown activity',
    activity: 'SynchronizedCountdownActivity & ClimbJumpActivity',
    volume: 0.85,
  },
  kiss_sound: {
    name: 'Real Kiss Sound Recording',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real kiss sound effect for facial countdown activity',
    activity: 'SynchronizedCountdownActivity',
    volume: 0.85,
  },
  tongue_pop: {
    name: 'Real Funny Tongue & Mouth Pop',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Funny tongue out pop sound for breaking visual lock',
    activity: 'CrazyFacesActivity',
    volume: 0.85,
  },
  wow_reaction: {
    name: 'Real Human Wow Reaction',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real human Wow encouragement for face decorator',
    activity: 'FaceDecoratorActivity',
    volume: 0.85,
  },
  rain_stream: {
    name: 'Real Gentle Rain Drops',
    url: 'https://cdn.freesound.org/previews/515/515664_11270278-lq.mp3',
    source: 'Freesound.org (#515664)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Real rain stream audio',
    activity: 'RainCloudActivity',
    volume: 0.85,
  },
  bag_zipper: {
    name: 'Real Bag Zipper & Fabric Movement',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Fabric bag rustle and zipper audio',
    activity: 'SurpriseBagShadowActivity',
    volume: 0.85,
  },
  swing_creak: {
    name: 'Real Playground Swing Chain Creak',
    url: 'https://cdn.freesound.org/previews/515/515664_11270278-lq.mp3',
    source: 'Freesound.org (#515664)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Outdoor playground swing chain motion sound',
    activity: 'SwingFlyActivity',
    volume: 0.80,
  },
  footsteps: {
    name: 'Real Footsteps on Floor Mat',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Footsteps on floor for climbing and tunnel activities',
    activity: 'ClimbJumpActivity & AdventureTunnelActivity',
    volume: 0.85,
  },
  tickle_gasp: {
    name: 'Real Tickling Human Laughter',
    url: 'https://cdn.freesound.org/previews/387/387431_7255428-lq.mp3',
    source: 'Freesound.org (#387431)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Playful social tickling laughter',
    activity: 'TwoTrainersActivity',
    volume: 0.85,
  },
  flashlight_switch: {
    name: 'Real Flashlight Switch Click',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Flashlight switch click for shadow theater',
    activity: 'ShadowTheaterActivity',
    volume: 0.80,
  },
  blocks_tap: {
    name: 'Real Wooden Blocks Tapping',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Wooden block placing & tapping sound',
    activity: 'NonVerbalCubesActivity',
    volume: 0.85,
  },
  chair_slide: {
    name: 'Real Wooden Chair Slide',
    url: 'https://cdn.freesound.org/previews/411/411089_5121236-lq.mp3',
    source: 'Freesound.org (#411089)',
    license: 'Creative Commons 0 / Public Domain',
    creator: 'Freesound Contributor',
    purpose: 'Wooden chair sliding for seat swap activity',
    activity: 'SeatSwapActivity',
    volume: 0.85,
  },
  // --- Arabic Cheering & Spoken Encouragement Audio Assets ---
  shater_hero: {
    name: 'شاطر شاطر يا بطل',
    url: '/audio/shater_hero.mp3',
    source: 'Local Arabic High Quality Recording',
    purpose: 'Arabic spoken celebration voice for all milestone achievements',
    volume: 0.95,
  },
  shater_short: {
    name: 'شاطر شاطر يا بطل (قصير)',
    url: '/audio/shater_short.mp3',
    source: 'Local Arabic High Quality Recording',
    purpose: 'Quick Arabic spoken praise',
    volume: 0.95,
  },
  shater_mumtaz: {
    name: 'شاطر شاطر أحسنت يا بطل',
    url: '/audio/shater_mumtaz.mp3',
    source: 'Local Arabic High Quality Recording',
    purpose: 'Arabic encouragement voice',
    volume: 0.95,
  },
  shater_abqari: {
    name: 'شاطر شاطر جداً يا عبقري',
    url: '/audio/shater_abqari.mp3',
    source: 'Local Arabic High Quality Recording',
    purpose: 'Arabic achievement praise',
    volume: 0.95,
  },
  ahsant_hero: {
    name: 'أحسنت يا بطل',
    url: '/audio/ahsant_hero.mp3',
    source: 'Local Arabic High Quality Recording',
    purpose: 'Arabic praise vocalization',
    volume: 0.95,
  },
};

